### ISSUE TITLE
[Q] Can the surrogate weights be loaded in timm's ViT?

### ISSUE THREAD

**Issue by NightMachinery** [suinleelab/vit-shapley#8]
Can the surrogate weights be loaded in timm's ViT? Which library is the model's parameter naming convention from?

**Comment by chanwkimlab** [comment]
Yes, we used the ViT implementation in the timm library (ver. 0.5.4), so I think that's possible unless the parameter naming convention of timm library has changed since the version: [https://github.com/suinleelab/vit-shapley/blob/master/vit_shapley/modules/vision_transformer.py](https://github.com/suinleelab/vit-shapley/blob/master/vit_shapley/modules/vision_transformer.py)

**Comment by NightMachinery** [comment]
@chanwkimlab Thanks! There are two files for each model:
```
https://aimslab.cs.washington.edu/vitshapley/checkpoints/ImageNette_vit_base_patch16_224_surrogate_3i6zzjnp.ckpt
https://aimslab.cs.washington.edu/vitshapley/checkpoints/ImageNette_vit_base_patch16_224_surrogate_3i6zzjnp_state_dict.ckpt
```
Am I correct in assuming that I only need to download the `state_dict.ckpt` files? Which is loadable using `torch.load`?

**Comment by NightMachinery** [comment]
For future reference:
- https://github.com/NightMachinery/decompv-libragrad-v1/blob/master/decompv/x/ds/main.py#L86
